from random import randint


prompt = """=============================================================================================================================\n
Welcome to Guess The Number. You need to guess the number which is between 0 and 20, both numbers included. Good luck.\n
=============================================================================================================================\n
To start the game, type 'Start' here > """

def randomNumber():
    """
    Creates a random number (integer) between 0 and 20.
    """
    number = randint(0,20)
    return number

def checkNumber(Guess: int, Number: int):
    """
    Checks if the number the user guessed is equal to the number generated by randomNumber().
    """
    if Guess == Number:
        guess = input(f'{Guess} was the correct number, congrats ')
        state = False
    elif Guess > Number:
        guess = int(input(f'Your guess was too high, try again: '))
        state = True
    else:
        guess = int(input(f'Your guess was too low, try again: '))
        state = True

    return guess, state

number = randomNumber()
state = True

while True:
    try:
        msg = input(prompt)
        if msg == "Start":
            number = randomNumber()
            print(number)
            guess = input("Enter your guess here: ")
            guess = int(guess)
            while state:
                test = checkNumber(guess, number)
                guess, state = test[0], test[1]
                print(f'Test: {test}')
                print(f'Guess: {guess}')
                print(f'State: {state}')

    except Exception as e:
        print(f'[ERROR]: {e}')